version: '2'
services:
    jobportal-app:
        image: jobportal
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jobportal-postgresql:5432/jobportal
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jobportal-elasticsearch:9300
        ports:
            - 8080:8080
    jobportal-postgresql:
        extends:
            file: postgresql.yml
            service: jobportal-postgresql
    jobportal-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jobportal-elasticsearch
